### PR TITLE
React todo app project

### PR DESCRIPTION
**Pull request by RWUBAKWANAYO**
# In this project we:

- Create react app
- Setup linter configuration
- Create project components
- Add event handling to the form
- Add project styles
- Add project routes
- Implement hurmberg menu
- Deploy the project to the Github
- Fix the linter error

### CODE REVIEW

**Review by benshidanny11 — APPROVED** [review]
Hi @RWUBAKWANAYO, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## To highlight 🎯

- No linter errors.✔️
- Good code design and implementation. ✔️
- Add all the requirements. ✔️

clap

Cheers and Happy coding!👏👏👏

**Comment by RWUBAKWANAYO** [comment]
merge changes to the development branch

**Comment by RWUBAKWANAYO** [comment]
Hi @benshidanny11,
I really appreciate the time and energy you put into this review process,
Thank you so much



Cheers and Happy coding!👏👏👏

**Review by benshidanny11 — COMMENTED** [review]
You're welcome @RWUBAKWANAYO

**Pull request merged**
